repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-json
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.0
  hooks:
  - id: clang-format
    types: [c]
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
  - id: cmake-lint
- repo: local
  hooks:
  - id: configure
    entry: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
    name: configure
    language: system
    pass_filenames: false
  - id: build
    entry: cmake --build build
    name: build
    language: system
    pass_filenames: false
  - id: clang-tidy
    entry: clang-tidy -p build
    name: clang-tidy
    language: python
    additional_dependencies: [clang-tidy]
    types: [c]
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
